disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- function_body_length
- cyclomatic_complexity
- file_length
- unused_optional_binding
- notification_center_detachment
- function_parameter_count
- line_length
- orphaned_doc_comment

type_body_length:
 - 1000 # warning
